In [1]:
from d3rlpy.datasets import get_cartpole

In [106]:
dataset, env = get_cartpole()

In [88]:
dataset.size()

1582

In [89]:
len(dataset.rewards)

99866

In [90]:
len(dataset.episodes)

1582

In [91]:
len(dataset.actions)

99866

In [107]:
from sklearn.model_selection import train_test_split

train_episodes, test_episodes = train_test_split(dataset, test_size=0.2)

In [108]:
from d3rlpy.algos import DQN

# if you don't use GPU, set use_gpu=False instead.
dqn = DQN(use_gpu=False)

# initialize neural networks with the given observation shape and action size.
# this is not necessary when you directly call fit or fit_online method.
dqn.build_with_dataset(dataset)

In [109]:
from d3rlpy.metrics.scorer import td_error_scorer
from d3rlpy.metrics.scorer import average_value_estimation_scorer

# calculate metrics with test dataset
td_error = td_error_scorer(dqn, test_episodes)

from d3rlpy.metrics.scorer import evaluate_on_environment

# set environment in scorer function, returns mean return per episode
evaluate_scorer = evaluate_on_environment(env)

# evaluate algorithm on the environment
rewards = evaluate_scorer(dqn)

In [30]:
env

<TimeLimit<CartPoleEnv<CartPole-v0>>>

In [ ]:
# Use the output of learning, this is the mean reward and the most useful metric to measure learning
dqn.fit(train_episodes,
        eval_episodes=test_episodes,
        n_epochs=10,
        scorers={
            'td_error': td_error_scorer,
            'value_scale': average_value_estimation_scorer,
            'environment': evaluate_scorer
        })

2023-03-13 17:56:23 [debug    ] RoundIterator is selected.
2023-03-13 17:56:23 [info     ] Directory is created at d3rlpy_logs/DQN_20230313175623
2023-03-13 17:56:23 [warning  ] Skip building models since they're already built.
2023-03-13 17:56:23 [info     ] Parameters are saved to d3rlpy_logs/DQN_20230313175623/params.json params={'action_scaler': None, 'batch_size': 32, 'encoder_factory': {'type': 'default', 'params': {'activation': 'relu', 'use_batch_norm': False, 'dropout_rate': None}}, 'gamma': 0.99, 'generated_maxlen': 100000, 'learning_rate': 6.25e-05, 'n_critics': 1, 'n_frames': 1, 'n_steps': 1, 'optim_factory': {'optim_cls': 'Adam', 'betas': (0.9, 0.999), 'eps': 1e-08, 'weight_decay': 0, 'amsgrad': False}, 'q_func_factory': {'type': 'mean', 'params': {'share_encoder': False}}, 'real_ratio': 1.0, 'reward_scaler': None, 'scaler': None, 'target_update_interval': 8000, 'use_gpu': None, 'algorithm': 'DQN', 'observation_shape': (4,), 'action_size': 2}


Epoch 1/10:   0%|          | 0/2528 [00:00<?, ?it/s]

2023-03-13 17:56:33 [info     ] DQN_20230313175623: epoch=1 step=2528 epoch=1 metrics={'time_sample_batch': 0.0001117969992794568, 'time_algorithm_update': 0.0031310268972493424, 'loss': 0.01063033081293939, 'time_step': 0.0033301781815818594, 'td_error': 0.9904131825877159, 'value_scale': 1.0364578913338531, 'environment': 9.7} step=2528
2023-03-13 17:56:33 [info     ] Model parameters are saved to d3rlpy_logs/DQN_20230313175623/model_2528.pt


Epoch 2/10:   0%|          | 0/2528 [00:00<?, ?it/s]

2023-03-13 17:56:43 [info     ] DQN_20230313175623: epoch=2 step=5056 epoch=2 metrics={'time_sample_batch': 0.00011344885901559757, 'time_algorithm_update': 0.00319484008263938, 'loss': 6.80640560042637e-05, 'time_step': 0.003397284806529178, 'td_error': 0.9925155655115155, 'value_scale': 1.0407329301160686, 'environment': 9.6} step=5056
2023-03-13 17:56:43 [info     ] Model parameters are saved to d3rlpy_logs/DQN_20230313175623/model_5056.pt


Epoch 3/10:   0%|          | 0/2528 [00:00<?, ?it/s]

2023-03-13 17:56:51 [info     ] DQN_20230313175623: epoch=3 step=7584 epoch=3 metrics={'time_sample_batch': 0.00010484966296183912, 'time_algorithm_update': 0.0029256843690630757, 'loss': 6.448426144561237e-05, 'time_step': 0.003113959031768992, 'td_error': 0.9924916739550745, 'value_scale': 1.0387473063789188, 'environment': 9.3} step=7584
2023-03-13 17:56:51 [info     ] Model parameters are saved to d3rlpy_logs/DQN_20230313175623/model_7584.pt


Epoch 4/10:   0%|          | 0/2528 [00:00<?, ?it/s]

2023-03-13 17:57:00 [info     ] DQN_20230313175623: epoch=4 step=10112 epoch=4 metrics={'time_sample_batch': 0.00010360767946967596, 'time_algorithm_update': 0.0029494544561905196, 'loss': 0.007633788344929161, 'time_step': 0.0031352091250540334, 'td_error': 0.9922751425525888, 'value_scale': 2.0111745741059113, 'environment': 13.0} step=10112
2023-03-13 17:57:00 [info     ] Model parameters are saved to d3rlpy_logs/DQN_20230313175623/model_10112.pt


Epoch 5/10:   0%|          | 0/2528 [00:00<?, ?it/s]

2023-03-13 17:57:09 [info     ] DQN_20230313175623: epoch=5 step=12640 epoch=5 metrics={'time_sample_batch': 0.00010387307103676133, 'time_algorithm_update': 0.0030028281521193587, 'loss': 0.006742560020579213, 'time_step': 0.0031877269473256946, 'td_error': 0.9891154735236134, 'value_scale': 2.0174748979198354, 'environment': 15.9} step=12640
2023-03-13 17:57:09 [info     ] Model parameters are saved to d3rlpy_logs/DQN_20230313175623/model_12640.pt


Epoch 6/10:   0%|          | 0/2528 [00:00<?, ?it/s]

### Metrics

**td_error** - larger td error means that the estimated state values are too far from the correct state values
The TD error is the difference between the correct reward based value and our estimate of the reward based value. The policy is the actor and the value function is the critic, with the ‘criticism’ being the TD error. If the TD error is positive the value of the action was greater than expected, suggesting the chosen action should be taken more often. If the TD error was negative the action had a lower value than expected, and so will be done less often in future states which are similar.

**discounted sum of average** - This is the discounted sum of advantage of the _**selected actions**_. This should be small to indicate that the policy selects actions with larger estimated values. This is the difference between the Q values of the dataset actions or the actions selected in each state and the max Q value according to the policy.  https://github.com/takuseno/d3rlpy/issues/99



In [51]:
observation = env.reset()

print(observation)

# return actions based on the greedy-policy
action = dqn.predict([observation])[0]

# estimate action-values
value = dqn.predict_value([observation], [action])

In [81]:
# This is the most useful metric for evaluating the progress of learning
def evaluate_mean_rewards(dqn):
    evaluate_scorer = evaluate_on_environment(env, n_trials=50)
    mean_episode_return = evaluate_scorer(dqn)
    return(mean_episode_return)

evaluate_mean_rewards(dqn)

200.0

In [54]:
value

In [49]:
dqn.predict([observation])

array([0])

### Generate offline data

In [105]:
import d3rlpy

# setup algorithm
random_policy = d3rlpy.algos.DiscreteRandomPolicy()

# prepare experience replay buffer
buffer = d3rlpy.online.buffers.ReplayBuffer(maxlen=500000, env=env)

# start data collection
random_policy.collect(env, buffer, n_steps=500000)

# export as MDPDataset
dataset = buffer.to_mdp_dataset()

# save MDPDataset
dataset.dump("random_policy_dataset_500000.h5")

2023-03-13 17:55:26 [debug    ] Building model...
2023-03-13 17:55:26 [debug    ] Model has been built.


  0%|          | 0/500000 [00:00<?, ?it/s]

In [33]:
ls

Intro_d3rlpy.ipynb                 random_policy_corridor_dataset.h5
d3rlpy_data/                       random_policy_dataset.h5
d3rlpy_logs/                       random_policy_dataset_80000.h5
poetry.lock                        trained_policy_dataset.h5
pyproject.toml                     trained_policy_dataset_80000.h5


In [96]:
# prepare experience replay buffer
buffer = d3rlpy.online.buffers.ReplayBuffer(maxlen=30000, env=env)

# start data collection
dqn.collect(env, buffer, n_steps=30000)

# export as MDPDataset
dataset = buffer.to_mdp_dataset()

# save MDPDataset
dataset.dump("trained_policy_dataset_30000.h5")

2023-03-13 17:53:00 [warning  ] Skip building models since they're already built.


  0%|          | 0/10000 [00:00<?, ?it/s]

import numpy as np

buffer = d3rlpy.online.buffers.ReplayBuffer(maxlen=80000, env=env)
dataset2 = buffer.to_mdp_dataset()
dataset2.load("random_policy_dataset_80000.h5")

buffer = d3rlpy.online.buffers.ReplayBuffer(maxlen=80000, env=env)
dataset3 = buffer.to_mdp_dataset()
dataset3.load("trained_policy_dataset_80000.h5")

In [97]:
dataset_trained = dataset.load("trained_policy_dataset_10000.h5")
dataset_random = dataset.load("random_policy_dataset_80000.h5")

In [98]:
train_episodes, test_episodes = train_test_split(dataset_trained, test_size=0.2)

In [99]:
dataset_trained.compute_stats()

{'return': {'mean': 199.0,
  'std': 0.0,
  'min': 199.0,
  'max': 199.0,
  'histogram': (array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 50,  0,  0,  0,  0,  0,  0,
           0,  0,  0]),
   array([198.5 , 198.55, 198.6 , 198.65, 198.7 , 198.75, 198.8 , 198.85,
          198.9 , 198.95, 199.  , 199.05, 199.1 , 199.15, 199.2 , 199.25,
          199.3 , 199.35, 199.4 , 199.45, 199.5 ], dtype=float32))},
 'reward': {'mean': 1.0,
  'std': 0.0,
  'min': 1.0,
  'max': 1.0,
  'histogram': (array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 9950,
             0,    0,    0,    0,    0,    0,    0,    0,    0]),
   array([0.5 , 0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ,
          1.05, 1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 ],
         dtype=float32))},
 'action': {'histogram': [[4941, 5009], array([0, 1])]},
 'observation': {'mean': array([0.13213772, 0.10073607, 0.00543183, 0.00063963], dtype=float32),
  'std': array([0.18628809, 0.62040365, 0.075

In [100]:
dataset_random.compute_stats()

{'return': {'mean': 22.129738,
  'std': 11.648639,
  'min': 8.0,
  'max': 94.0,
  'histogram': (array([570, 835, 679, 547, 284, 187, 175,  95,  75,  56,  43,  15,  15,
           12,  11,   3,   7,   2,   2,   2]),
   array([ 8. , 12.3, 16.6, 20.9, 25.2, 29.5, 33.8, 38.1, 42.4, 46.7, 51. ,
          55.3, 59.6, 63.9, 68.2, 72.5, 76.8, 81.1, 85.4, 89.7, 94. ],
         dtype=float32))},
 'reward': {'mean': 1.0,
  'std': 0.0,
  'min': 1.0,
  'max': 1.0,
  'histogram': (array([    0,     0,     0,     0,     0,     0,     0,     0,     0,
              0, 79999,     0,     0,     0,     0,     0,     0,     0,
              0,     0]),
   array([0.5 , 0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ,
          1.05, 1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 ],
         dtype=float32))},
 'action': {'histogram': [[40042, 39957], array([0, 1])]},
 'observation': {'mean': array([ 0.00129826,  0.00506058,  0.00047018, -0.00162286], dtype=float32),
  'std': array([0.0945581

In [101]:
dataset_trained.actions

array([0, 0, 0, ..., 1, 0, 0], dtype=int32)

In [76]:
dataset_random.actions

array([1, 1, 1, ..., 0, 0, 0], dtype=int32)

In [57]:
dataset_trained.rewards

array([1., 1., 1., ..., 1., 1., 1.], dtype=float32)

In [102]:
len(dataset_trained.episodes)

50

In [78]:
len(dataset_random.episodes)

3615

In [79]:
dataset_trained.observations

array([[ 0.02962353, -0.0323091 , -0.03679555,  0.03139311],
       [ 0.02897735, -0.22688459, -0.03616769,  0.31224334],
       [ 0.02443966, -0.42147312, -0.02992282,  0.5933043 ],
       ...,
       [ 0.2347083 ,  0.5337355 , -0.13025276, -0.45787495],
       [ 0.24538301,  0.34067228, -0.13941026, -0.20891936],
       [ 0.25219646,  0.14779048, -0.14358865,  0.03674239]],
      dtype=float32)

### Train on offline data

In [103]:
from d3rlpy.algos import DQN
from d3rlpy.metrics.scorer import evaluate_on_environment

# if you don't use GPU, set use_gpu=False instead.
dqn = DQN(use_gpu=False)

# initialize neural networks with the given observation shape and action size.
# this is not necessary when you directly call fit or fit_online method.
dqn.build_with_dataset(dataset_trained)

# calculate metrics with test dataset
td_error = td_error_scorer(dqn, test_episodes)

# set environment in scorer function, returns mean return per episode
evaluate_scorer = evaluate_on_environment(env)

# evaluate algorithm on the environment
rewards = evaluate_scorer(dqn)

# Use the output of learning, this is the mean reward and the most useful metric to measure learning
dqn.fit(train_episodes,
        eval_episodes=test_episodes,
        n_epochs=10,
        scorers={
            'td_error': td_error_scorer,
            'value_scale': average_value_estimation_scorer,
            'environment': evaluate_scorer
        })

2023-03-13 17:53:44 [debug    ] RoundIterator is selected.
2023-03-13 17:53:44 [info     ] Directory is created at d3rlpy_logs/DQN_20230313175344
2023-03-13 17:53:44 [warning  ] Skip building models since they're already built.
2023-03-13 17:53:44 [info     ] Parameters are saved to d3rlpy_logs/DQN_20230313175344/params.json params={'action_scaler': None, 'batch_size': 32, 'encoder_factory': {'type': 'default', 'params': {'activation': 'relu', 'use_batch_norm': False, 'dropout_rate': None}}, 'gamma': 0.99, 'generated_maxlen': 100000, 'learning_rate': 6.25e-05, 'n_critics': 1, 'n_frames': 1, 'n_steps': 1, 'optim_factory': {'optim_cls': 'Adam', 'betas': (0.9, 0.999), 'eps': 1e-08, 'weight_decay': 0, 'amsgrad': False}, 'q_func_factory': {'type': 'mean', 'params': {'share_encoder': False}}, 'real_ratio': 1.0, 'reward_scaler': None, 'scaler': None, 'target_update_interval': 8000, 'use_gpu': None, 'algorithm': 'DQN', 'observation_shape': (4,), 'action_size': 2}


Epoch 1/10:   0%|          | 0/247 [00:00<?, ?it/s]

2023-03-13 17:53:45 [info     ] DQN_20230313175344: epoch=1 step=247 epoch=1 metrics={'time_sample_batch': 0.00010931733166157959, 'time_algorithm_update': 0.0029924823204998062, 'loss': 0.09647901264030623, 'time_step': 0.003175637017377475, 'td_error': 1.0875713358021746, 'value_scale': 1.21059853401449, 'environment': 9.4} step=247
2023-03-13 17:53:45 [info     ] Model parameters are saved to d3rlpy_logs/DQN_20230313175344/model_247.pt


Epoch 2/10:   0%|          | 0/247 [00:00<?, ?it/s]

2023-03-13 17:53:46 [info     ] DQN_20230313175344: epoch=2 step=494 epoch=2 metrics={'time_sample_batch': 0.00010588391107103603, 'time_algorithm_update': 0.0029034875182487705, 'loss': 0.0025412102405694484, 'time_step': 0.003082730026862882, 'td_error': 1.0419111711208267, 'value_scale': 1.2066537923283047, 'environment': 9.6} step=494
2023-03-13 17:53:46 [info     ] Model parameters are saved to d3rlpy_logs/DQN_20230313175344/model_494.pt


Epoch 3/10:   0%|          | 0/247 [00:00<?, ?it/s]

2023-03-13 17:53:47 [info     ] DQN_20230313175344: epoch=3 step=741 epoch=3 metrics={'time_sample_batch': 0.000105486225020065, 'time_algorithm_update': 0.0029719281293119977, 'loss': 0.0004847896664058375, 'time_step': 0.003149926421130717, 'td_error': 1.0239347641817247, 'value_scale': 1.203045593668716, 'environment': 9.7} step=741
2023-03-13 17:53:47 [info     ] Model parameters are saved to d3rlpy_logs/DQN_20230313175344/model_741.pt


Epoch 4/10:   0%|          | 0/247 [00:00<?, ?it/s]

2023-03-13 17:53:48 [info     ] DQN_20230313175344: epoch=4 step=988 epoch=4 metrics={'time_sample_batch': 0.00011140518342917747, 'time_algorithm_update': 0.0031462458946444243, 'loss': 0.0001318362137165603, 'time_step': 0.0033343523620111256, 'td_error': 1.018758237361908, 'value_scale': 1.1978413529468306, 'environment': 9.0} step=988
2023-03-13 17:53:48 [info     ] Model parameters are saved to d3rlpy_logs/DQN_20230313175344/model_988.pt


Epoch 5/10:   0%|          | 0/247 [00:00<?, ?it/s]

2023-03-13 17:53:49 [info     ] DQN_20230313175344: epoch=5 step=1235 epoch=5 metrics={'time_sample_batch': 0.00011581834028606955, 'time_algorithm_update': 0.00327252665994621, 'loss': 6.862798694385449e-05, 'time_step': 0.0034672818203204075, 'td_error': 1.0144563158052136, 'value_scale': 1.194837223038529, 'environment': 9.7} step=1235
2023-03-13 17:53:49 [info     ] Model parameters are saved to d3rlpy_logs/DQN_20230313175344/model_1235.pt


Epoch 6/10:   0%|          | 0/247 [00:00<?, ?it/s]

2023-03-13 17:53:50 [info     ] DQN_20230313175344: epoch=6 step=1482 epoch=6 metrics={'time_sample_batch': 0.0001034176784005725, 'time_algorithm_update': 0.0029782051982184653, 'loss': 5.0835522290388486e-05, 'time_step': 0.0031542150597823294, 'td_error': 1.0120382318593035, 'value_scale': 1.195711729321817, 'environment': 9.9} step=1482
2023-03-13 17:53:50 [info     ] Model parameters are saved to d3rlpy_logs/DQN_20230313175344/model_1482.pt


Epoch 7/10:   0%|          | 0/247 [00:00<?, ?it/s]

2023-03-13 17:53:50 [info     ] DQN_20230313175344: epoch=7 step=1729 epoch=7 metrics={'time_sample_batch': 0.00010324393206762398, 'time_algorithm_update': 0.0029864697321223825, 'loss': 3.9984738121325524e-05, 'time_step': 0.0031596340148555124, 'td_error': 1.0131008351993078, 'value_scale': 1.194240144467113, 'environment': 9.9} step=1729
2023-03-13 17:53:50 [info     ] Model parameters are saved to d3rlpy_logs/DQN_20230313175344/model_1729.pt


Epoch 8/10:   0%|          | 0/247 [00:00<?, ?it/s]

2023-03-13 17:53:51 [info     ] DQN_20230313175344: epoch=8 step=1976 epoch=8 metrics={'time_sample_batch': 0.00010310976128829153, 'time_algorithm_update': 0.0030097411229060246, 'loss': 3.141530283858956e-05, 'time_step': 0.003184291515273121, 'td_error': 1.012402426564332, 'value_scale': 1.1949137575096553, 'environment': 9.8} step=1976
2023-03-13 17:53:51 [info     ] Model parameters are saved to d3rlpy_logs/DQN_20230313175344/model_1976.pt


Epoch 9/10:   0%|          | 0/247 [00:00<?, ?it/s]

2023-03-13 17:53:52 [info     ] DQN_20230313175344: epoch=9 step=2223 epoch=9 metrics={'time_sample_batch': 0.00010311748334753369, 'time_algorithm_update': 0.0030107671915278263, 'loss': 2.4545441545946202e-05, 'time_step': 0.0031812162051799327, 'td_error': 1.0122608189329956, 'value_scale': 1.194244753832769, 'environment': 9.7} step=2223
2023-03-13 17:53:52 [info     ] Model parameters are saved to d3rlpy_logs/DQN_20230313175344/model_2223.pt


Epoch 10/10:   0%|          | 0/247 [00:00<?, ?it/s]

2023-03-13 17:53:53 [info     ] DQN_20230313175344: epoch=10 step=2470 epoch=10 metrics={'time_sample_batch': 0.00010251033643961919, 'time_algorithm_update': 0.002960612416750024, 'loss': 1.917358991954919e-05, 'time_step': 0.003131594252489839, 'td_error': 1.011475711519068, 'value_scale': 1.1941286064157581, 'environment': 9.3} step=2470
2023-03-13 17:53:53 [info     ] Model parameters are saved to d3rlpy_logs/DQN_20230313175344/model_2470.pt


[(1,
  {'time_sample_batch': 0.00010931733166157959,
   'time_algorithm_update': 0.0029924823204998062,
   'loss': 0.09647901264030623,
   'time_step': 0.003175637017377475,
   'td_error': 1.0875713358021746,
   'value_scale': 1.21059853401449,
   'environment': 9.4}),
 (2,
  {'time_sample_batch': 0.00010588391107103603,
   'time_algorithm_update': 0.0029034875182487705,
   'loss': 0.0025412102405694484,
   'time_step': 0.003082730026862882,
   'td_error': 1.0419111711208267,
   'value_scale': 1.2066537923283047,
   'environment': 9.6}),
 (3,
  {'time_sample_batch': 0.000105486225020065,
   'time_algorithm_update': 0.0029719281293119977,
   'loss': 0.0004847896664058375,
   'time_step': 0.003149926421130717,
   'td_error': 1.0239347641817247,
   'value_scale': 1.203045593668716,
   'environment': 9.7}),
 (4,
  {'time_sample_batch': 0.00011140518342917747,
   'time_algorithm_update': 0.0031462458946444243,
   'loss': 0.0001318362137165603,
   'time_step': 0.0033343523620111256,
   'td_e

In [104]:
evaluate_mean_rewards(dqn)

9.44

In [84]:
train_episodes, test_episodes = train_test_split(dataset_random, test_size=0.2)

In [85]:
from d3rlpy.algos import DQN
from d3rlpy.metrics.scorer import evaluate_on_environment

# if you don't use GPU, set use_gpu=False instead.
dqn = DQN(use_gpu=False)

# initialize neural networks with the given observation shape and action size.
# this is not necessary when you directly call fit or fit_online method.
dqn.build_with_dataset(dataset_random)

# calculate metrics with test dataset
td_error = td_error_scorer(dqn, test_episodes)

# set environment in scorer function, returns mean return per episode
evaluate_scorer = evaluate_on_environment(env)

# evaluate algorithm on the environment
rewards = evaluate_scorer(dqn)

# Use the output of learning, this is the mean reward and the most useful metric to measure learning
dqn.fit(train_episodes,
        eval_episodes=test_episodes,
        n_epochs=10,
        scorers={
            'td_error': td_error_scorer,
            'value_scale': average_value_estimation_scorer,
            'environment': evaluate_scorer
        })

2023-03-13 17:34:57 [debug    ] RoundIterator is selected.
2023-03-13 17:34:57 [info     ] Directory is created at d3rlpy_logs/DQN_20230313173457
2023-03-13 17:34:57 [warning  ] Skip building models since they're already built.
2023-03-13 17:34:57 [info     ] Parameters are saved to d3rlpy_logs/DQN_20230313173457/params.json params={'action_scaler': None, 'batch_size': 32, 'encoder_factory': {'type': 'default', 'params': {'activation': 'relu', 'use_batch_norm': False, 'dropout_rate': None}}, 'gamma': 0.99, 'generated_maxlen': 100000, 'learning_rate': 6.25e-05, 'n_critics': 1, 'n_frames': 1, 'n_steps': 1, 'optim_factory': {'optim_cls': 'Adam', 'betas': (0.9, 0.999), 'eps': 1e-08, 'weight_decay': 0, 'amsgrad': False}, 'q_func_factory': {'type': 'mean', 'params': {'share_encoder': False}}, 'real_ratio': 1.0, 'reward_scaler': None, 'scaler': None, 'target_update_interval': 8000, 'use_gpu': None, 'algorithm': 'DQN', 'observation_shape': (4,), 'action_size': 2}


Epoch 1/10:   0%|          | 0/1995 [00:00<?, ?it/s]

2023-03-13 17:35:05 [info     ] DQN_20230313173457: epoch=1 step=1995 epoch=1 metrics={'time_sample_batch': 0.00010886168420165403, 'time_algorithm_update': 0.002959556866409187, 'loss': 0.014313800445492882, 'time_step': 0.0031524298483865303, 'td_error': 0.978216586846662, 'value_scale': 1.0589266722826343, 'environment': 9.0} step=1995
2023-03-13 17:35:05 [info     ] Model parameters are saved to d3rlpy_logs/DQN_20230313173457/model_1995.pt


Epoch 2/10:   0%|          | 0/1995 [00:00<?, ?it/s]

2023-03-13 17:35:13 [info     ] DQN_20230313173457: epoch=2 step=3990 epoch=2 metrics={'time_sample_batch': 9.834784314148408e-05, 'time_algorithm_update': 0.0028192679087320964, 'loss': 0.000291367196469926, 'time_step': 0.0029867383770476605, 'td_error': 0.9701512011910716, 'value_scale': 1.0643255414203694, 'environment': 10.3} step=3990
2023-03-13 17:35:13 [info     ] Model parameters are saved to d3rlpy_logs/DQN_20230313173457/model_3990.pt


Epoch 3/10:   0%|          | 0/1995 [00:00<?, ?it/s]

2023-03-13 17:35:21 [info     ] DQN_20230313173457: epoch=3 step=5985 epoch=3 metrics={'time_sample_batch': 0.00010003075563817992, 'time_algorithm_update': 0.002889738704327653, 'loss': 0.0002578747330350818, 'time_step': 0.0030609396167267534, 'td_error': 0.9703398817385191, 'value_scale': 1.062563999074589, 'environment': 9.7} step=5985
2023-03-13 17:35:21 [info     ] Model parameters are saved to d3rlpy_logs/DQN_20230313173457/model_5985.pt


Epoch 4/10:   0%|          | 0/1995 [00:00<?, ?it/s]

2023-03-13 17:35:28 [info     ] DQN_20230313173457: epoch=4 step=7980 epoch=4 metrics={'time_sample_batch': 9.771516747343212e-05, 'time_algorithm_update': 0.0028324815563689496, 'loss': 0.00023306020324215886, 'time_step': 0.002999182392780046, 'td_error': 0.9794813734559903, 'value_scale': 1.0660120074316712, 'environment': 13.3} step=7980
2023-03-13 17:35:28 [info     ] Model parameters are saved to d3rlpy_logs/DQN_20230313173457/model_7980.pt


Epoch 5/10:   0%|          | 0/1995 [00:00<?, ?it/s]

2023-03-13 17:35:36 [info     ] DQN_20230313173457: epoch=5 step=9975 epoch=5 metrics={'time_sample_batch': 9.783754372656494e-05, 'time_algorithm_update': 0.002884395140454285, 'loss': 0.01768109599737668, 'time_step': 0.003051576877297614, 'td_error': 0.9405802728373429, 'value_scale': 2.032548883373756, 'environment': 11.5} step=9975
2023-03-13 17:35:36 [info     ] Model parameters are saved to d3rlpy_logs/DQN_20230313173457/model_9975.pt


Epoch 6/10:   0%|          | 0/1995 [00:00<?, ?it/s]

2023-03-13 17:35:44 [info     ] DQN_20230313173457: epoch=6 step=11970 epoch=6 metrics={'time_sample_batch': 9.19016979093241e-05, 'time_algorithm_update': 0.0028482257871699514, 'loss': 0.01348649567968497, 'time_step': 0.0030017690252241934, 'td_error': 0.9651308028829698, 'value_scale': 2.035894104555085, 'environment': 9.7} step=11970
2023-03-13 17:35:44 [info     ] Model parameters are saved to d3rlpy_logs/DQN_20230313173457/model_11970.pt


Epoch 7/10:   0%|          | 0/1995 [00:00<?, ?it/s]

2023-03-13 17:35:52 [info     ] DQN_20230313173457: epoch=7 step=13965 epoch=7 metrics={'time_sample_batch': 9.319632872005453e-05, 'time_algorithm_update': 0.0029096635660730806, 'loss': 0.012340723378887227, 'time_step': 0.0030651372178156573, 'td_error': 0.9162572047515058, 'value_scale': 2.0004651960955484, 'environment': 11.5} step=13965
2023-03-13 17:35:52 [info     ] Model parameters are saved to d3rlpy_logs/DQN_20230313173457/model_13965.pt


Epoch 8/10:   0%|          | 0/1995 [00:00<?, ?it/s]

2023-03-13 17:36:00 [info     ] DQN_20230313173457: epoch=8 step=15960 epoch=8 metrics={'time_sample_batch': 9.00054635260637e-05, 'time_algorithm_update': 0.0027645108693823183, 'loss': 0.011448570002727608, 'time_step': 0.002915068796105253, 'td_error': 0.925025285600246, 'value_scale': 2.0062189445773058, 'environment': 9.7} step=15960
2023-03-13 17:36:00 [info     ] Model parameters are saved to d3rlpy_logs/DQN_20230313173457/model_15960.pt


Epoch 9/10:   0%|          | 0/1995 [00:00<?, ?it/s]

2023-03-13 17:36:07 [info     ] DQN_20230313173457: epoch=9 step=17955 epoch=9 metrics={'time_sample_batch': 9.976795741489955e-05, 'time_algorithm_update': 0.002914592436979289, 'loss': 0.026899029059819342, 'time_step': 0.0030874456678118022, 'td_error': 0.9212762029593982, 'value_scale': 2.977290669963741, 'environment': 9.8} step=17955
2023-03-13 17:36:07 [info     ] Model parameters are saved to d3rlpy_logs/DQN_20230313173457/model_17955.pt


Epoch 10/10:   0%|          | 0/1995 [00:00<?, ?it/s]

2023-03-13 17:36:15 [info     ] DQN_20230313173457: epoch=10 step=19950 epoch=10 metrics={'time_sample_batch': 9.591442002987204e-05, 'time_algorithm_update': 0.002864971376003179, 'loss': 0.02173981322823174, 'time_step': 0.003028388847982077, 'td_error': 0.9045235252656997, 'value_scale': 2.955735904216205, 'environment': 10.2} step=19950
2023-03-13 17:36:15 [info     ] Model parameters are saved to d3rlpy_logs/DQN_20230313173457/model_19950.pt


[(1,
  {'time_sample_batch': 0.00010886168420165403,
   'time_algorithm_update': 0.002959556866409187,
   'loss': 0.014313800445492882,
   'time_step': 0.0031524298483865303,
   'td_error': 0.978216586846662,
   'value_scale': 1.0589266722826343,
   'environment': 9.0}),
 (2,
  {'time_sample_batch': 9.834784314148408e-05,
   'time_algorithm_update': 0.0028192679087320964,
   'loss': 0.000291367196469926,
   'time_step': 0.0029867383770476605,
   'td_error': 0.9701512011910716,
   'value_scale': 1.0643255414203694,
   'environment': 10.3}),
 (3,
  {'time_sample_batch': 0.00010003075563817992,
   'time_algorithm_update': 0.002889738704327653,
   'loss': 0.0002578747330350818,
   'time_step': 0.0030609396167267534,
   'td_error': 0.9703398817385191,
   'value_scale': 1.062563999074589,
   'environment': 9.7}),
 (4,
  {'time_sample_batch': 9.771516747343212e-05,
   'time_algorithm_update': 0.0028324815563689496,
   'loss': 0.00023306020324215886,
   'time_step': 0.002999182392780046,
   't

In [86]:
evaluate_mean_rewards(dqn)

10.86

### Samples from the random set do not result in good learning. You always want to generate samples using a trained policy

In [46]:
from d3rlpy.dataset import MDPDataset
from d3rlpy.algos import DiscreteCQL

# setup CQL algorithm (discrete version)
cql = DiscreteCQL(n_frames=4, scaler='pixel', use_gpu=False)

# split train and test episodes
train_episodes, test_episodes = train_test_split(dataset2, test_size=0.2)

In [47]:
from d3rlpy.metrics.scorer import discounted_sum_of_advantage_scorer
from d3rlpy.metrics.scorer import evaluate_on_environment
from d3rlpy.metrics.scorer import td_error_scorer
from d3rlpy.metrics.scorer import average_value_estimation_scorer

# start training
cql.fit(train_episodes,
        eval_episodes=test_episodes,
        n_epochs=10,
        scorers={
            'environment': evaluate_on_environment(env), # Cartpole environment
            'advantage': discounted_sum_of_advantage_scorer, # smaller is better
            'td_error': td_error_scorer, # smaller is better
            'value_scale': average_value_estimation_scorer # smaller is better
        })

2023-03-10 13:58:19 [debug    ] RoundIterator is selected.
2023-03-10 13:58:19 [info     ] Directory is created at d3rlpy_logs/DiscreteCQL_20230310135819
2023-03-10 13:58:19 [debug    ] Fitting scaler...              scaler=pixel
2023-03-10 13:58:19 [debug    ] Building models...
2023-03-10 13:58:19 [debug    ] Models have been built.
2023-03-10 13:58:19 [info     ] Parameters are saved to d3rlpy_logs/DiscreteCQL_20230310135819/params.json params={'action_scaler': None, 'alpha': 1.0, 'batch_size': 32, 'encoder_factory': {'type': 'default', 'params': {'activation': 'relu', 'use_batch_norm': False, 'dropout_rate': None}}, 'gamma': 0.99, 'generated_maxlen': 100000, 'learning_rate': 6.25e-05, 'n_critics': 1, 'n_frames': 4, 'n_steps': 1, 'optim_factory': {'optim_cls': 'Adam', 'betas': (0.9, 0.999), 'eps': 1e-08, 'weight_decay': 0, 'amsgrad': False}, 'q_func_factory': {'type': 'mean', 'params': {'share_encoder': False}}, 'real_ratio': 1.0, 'reward_scaler': None, 'scaler': {'type': 'pixel', '

Epoch 1/10:   0%|          | 0/2475 [00:00<?, ?it/s]

2023-03-10 13:58:33 [info     ] DiscreteCQL_20230310135819: epoch=1 step=2475 epoch=1 metrics={'time_sample_batch': 0.00011373096042209202, 'time_algorithm_update': 0.0048319306999746, 'loss': 0.7044372973056755, 'time_step': 0.005021619122437757, 'environment': 9.7, 'advantage': -0.7184256813428528, 'td_error': 1.003873027455517, 'value_scale': 1.0141254830004633} step=2475
2023-03-10 13:58:33 [info     ] Model parameters are saved to d3rlpy_logs/DiscreteCQL_20230310135819/model_2475.pt


Epoch 2/10:   0%|          | 0/2475 [00:00<?, ?it/s]

2023-03-10 13:58:47 [info     ] DiscreteCQL_20230310135819: epoch=2 step=4950 epoch=2 metrics={'time_sample_batch': 0.00010732737454501066, 'time_algorithm_update': 0.004808726936879784, 'loss': 0.6926807059904542, 'time_step': 0.004982993386008523, 'environment': 9.6, 'advantage': -0.8237623272107137, 'td_error': 1.0083632118101098, 'value_scale': 1.016894909017989} step=4950
2023-03-10 13:58:47 [info     ] Model parameters are saved to d3rlpy_logs/DiscreteCQL_20230310135819/model_4950.pt


Epoch 3/10:   0%|          | 0/2475 [00:00<?, ?it/s]

2023-03-10 13:58:59 [info     ] DiscreteCQL_20230310135819: epoch=3 step=7425 epoch=3 metrics={'time_sample_batch': 0.0001019903626104798, 'time_algorithm_update': 0.004526491646814828, 'loss': 0.692025963369042, 'time_step': 0.0046929629162104445, 'environment': 9.2, 'advantage': -1.4125308991548584, 'td_error': 1.0304378637299039, 'value_scale': 1.0262357572453116} step=7425
2023-03-10 13:58:59 [info     ] Model parameters are saved to d3rlpy_logs/DiscreteCQL_20230310135819/model_7425.pt


Epoch 4/10:   0%|          | 0/2475 [00:00<?, ?it/s]

2023-03-10 13:59:13 [info     ] DiscreteCQL_20230310135819: epoch=4 step=9900 epoch=4 metrics={'time_sample_batch': 0.00010997589188392716, 'time_algorithm_update': 0.004905999308884746, 'loss': 0.6936927360236043, 'time_step': 0.005086273906206844, 'environment': 22.6, 'advantage': -0.3006639996273257, 'td_error': 0.9743382934822494, 'value_scale': 2.0003800274591748} step=9900
2023-03-10 13:59:13 [info     ] Model parameters are saved to d3rlpy_logs/DiscreteCQL_20230310135819/model_9900.pt


Epoch 5/10:   0%|          | 0/2475 [00:00<?, ?it/s]

2023-03-10 13:59:27 [info     ] DiscreteCQL_20230310135819: epoch=5 step=12375 epoch=5 metrics={'time_sample_batch': 0.0001084217880711411, 'time_algorithm_update': 0.004895942187068438, 'loss': 0.6897469291542515, 'time_step': 0.00507350459243312, 'environment': 11.9, 'advantage': -1.7485878148839962, 'td_error': 1.0283506860403937, 'value_scale': 2.0208384595941564} step=12375
2023-03-10 13:59:27 [info     ] Model parameters are saved to d3rlpy_logs/DiscreteCQL_20230310135819/model_12375.pt


Epoch 6/10:   0%|          | 0/2475 [00:00<?, ?it/s]

2023-03-10 13:59:40 [info     ] DiscreteCQL_20230310135819: epoch=6 step=14850 epoch=6 metrics={'time_sample_batch': 0.00010091974277688999, 'time_algorithm_update': 0.004574159757055418, 'loss': 0.686699037840872, 'time_step': 0.004739959119546293, 'environment': 25.9, 'advantage': -0.8160245403421296, 'td_error': 1.0020592841492546, 'value_scale': 2.0106483820014636} step=14850
2023-03-10 13:59:40 [info     ] Model parameters are saved to d3rlpy_logs/DiscreteCQL_20230310135819/model_14850.pt


Epoch 7/10:   0%|          | 0/2475 [00:00<?, ?it/s]

2023-03-10 13:59:52 [info     ] DiscreteCQL_20230310135819: epoch=7 step=17325 epoch=7 metrics={'time_sample_batch': 0.00010110190420439749, 'time_algorithm_update': 0.004474106316614632, 'loss': 0.6857365346195722, 'time_step': 0.004640489154391818, 'environment': 17.5, 'advantage': -2.433293339287986, 'td_error': 1.0552107648111715, 'value_scale': 3.0459035404557544} step=17325
2023-03-10 13:59:52 [info     ] Model parameters are saved to d3rlpy_logs/DiscreteCQL_20230310135819/model_17325.pt


Epoch 8/10:   0%|          | 0/2475 [00:00<?, ?it/s]

2023-03-10 14:00:06 [info     ] DiscreteCQL_20230310135819: epoch=8 step=19800 epoch=8 metrics={'time_sample_batch': 0.00010647542548902106, 'time_algorithm_update': 0.004866572293368253, 'loss': 0.6805609355791651, 'time_step': 0.005041583186448223, 'environment': 58.7, 'advantage': -2.9189308941082848, 'td_error': 1.061670664012514, 'value_scale': 3.046021322604366} step=19800
2023-03-10 14:00:06 [info     ] Model parameters are saved to d3rlpy_logs/DiscreteCQL_20230310135819/model_19800.pt


Epoch 9/10:   0%|          | 0/2475 [00:00<?, ?it/s]

2023-03-10 14:00:20 [info     ] DiscreteCQL_20230310135819: epoch=9 step=22275 epoch=9 metrics={'time_sample_batch': 0.00010994246511748343, 'time_algorithm_update': 0.0049418311648898655, 'loss': 0.6768818291991648, 'time_step': 0.005123888940522165, 'environment': 25.4, 'advantage': -2.5767650129123534, 'td_error': 1.087821161304596, 'value_scale': 3.061811562537585} step=22275
2023-03-10 14:00:20 [info     ] Model parameters are saved to d3rlpy_logs/DiscreteCQL_20230310135819/model_22275.pt


Epoch 10/10:   0%|          | 0/2475 [00:00<?, ?it/s]

2023-03-10 14:00:33 [info     ] DiscreteCQL_20230310135819: epoch=10 step=24750 epoch=10 metrics={'time_sample_batch': 0.00010402534947250829, 'time_algorithm_update': 0.004621366539386788, 'loss': 0.678041718006134, 'time_step': 0.004792209490381106, 'environment': 105.7, 'advantage': -2.5476583313030563, 'td_error': 1.066795705757112, 'value_scale': 4.074616679151892} step=24750
2023-03-10 14:00:33 [info     ] Model parameters are saved to d3rlpy_logs/DiscreteCQL_20230310135819/model_24750.pt


[(1,
  {'time_sample_batch': 0.00011373096042209202,
   'time_algorithm_update': 0.0048319306999746,
   'loss': 0.7044372973056755,
   'time_step': 0.005021619122437757,
   'environment': 9.7,
   'advantage': -0.7184256813428528,
   'td_error': 1.003873027455517,
   'value_scale': 1.0141254830004633}),
 (2,
  {'time_sample_batch': 0.00010732737454501066,
   'time_algorithm_update': 0.004808726936879784,
   'loss': 0.6926807059904542,
   'time_step': 0.004982993386008523,
   'environment': 9.6,
   'advantage': -0.8237623272107137,
   'td_error': 1.0083632118101098,
   'value_scale': 1.016894909017989}),
 (3,
  {'time_sample_batch': 0.0001019903626104798,
   'time_algorithm_update': 0.004526491646814828,
   'loss': 0.692025963369042,
   'time_step': 0.0046929629162104445,
   'environment': 9.2,
   'advantage': -1.4125308991548584,
   'td_error': 1.0304378637299039,
   'value_scale': 1.0262357572453116}),
 (4,
  {'time_sample_batch': 0.00010997589188392716,
   'time_algorithm_update': 0.0

### Custom environment

In [104]:
import gym
from gym.spaces import Discrete, Box
import numpy as np
import os
import random

class SimpleCorridor_d3rlpy(gym.Env):
    """Example of a custom env in which you have to walk down a corridor.
    Get a reward of -0.1 if you are not at the end, a random reward that is positive if you do.
    Move +1 if you move forward, -1 if you move backward. The total length is 5.
    We should want to reach the end in 5 steps in the perfectly trained world. 
    You can configure the length of the corridor via the env config."""

    def __init__(self, config):
        self.end_pos = config["corridor_length"]
        self.cur_pos = 0
        self.action_space = Discrete(5)
        self.observation_space = Box(0.0, self.end_pos, shape=(1,), dtype=np.float32)
        # Set the seed. This is only used for the final (reach goal) reward.
        self.reset()

    def reset(self, *, seed=None, options=None):
        random.seed(seed)
        self.cur_pos = 0
        return np.array([self.cur_pos])

    def step(self, action):
        assert action in [0, 1, 2, 3, 4], action
        # backward step
        if action == 0 and self.cur_pos > 0:
            self.cur_pos -= 1
            reward = -0.2
        # forward step
        elif action == 1:
            self.cur_pos += 1
            if(self.check_if_water()):
                reward = -0.5
            else:
                reward = 0.1
        # double speed
        elif action == 4:
            if(self.cur_pos <= 3):
                self.cur_pos += 2
            else:
                self.cur_pos += 1
            if(self.check_if_water()):
                reward = -0.5
            else:
                reward = 0.2
        # left or right
        else:
            self.cur_pos = self.cur_pos
            reward = -0.05
            
        done = truncated = self.cur_pos >= self.end_pos
        if(done):
            reward = 2
        # Produce a random reward when we reach the goal.
        return (
            np.array([self.cur_pos]),
            reward, # Setting to 2 instead of random reward has no real impact
            done,
            {},
        )
    
    def check_if_water(self):
        # This is water and will get a negative reward
        if(self.cur_pos == 3):
            return True
        else:
            return False

config={"corridor_length": 5}
env = SimpleCorridor_d3rlpy(config=config)

In [105]:
env

In [106]:
env.reset()

array([0])

In [108]:
action = env.action_space.sample()
obs, reward, done, info = env.step(action)

In [109]:
reward

0.2

In [102]:
obs.astype

<function ndarray.astype>

In [138]:
# setup algorithm
random_policy = d3rlpy.algos.DiscreteRandomPolicy()

# prepare experience replay buffer
buffer = d3rlpy.online.buffers.ReplayBuffer(maxlen=100000, env=env)

# start data collection
random_policy.collect(env, buffer, n_steps=100000)

# export as MDPDataset
dataset = buffer.to_mdp_dataset()

# save MDPDataset
dataset.dump("random_policy_corridor_dataset.h5")

2023-03-10 15:47:33 [debug    ] Building model...
2023-03-10 15:47:33 [debug    ] Model has been built.


  0%|          | 0/100000 [00:00<?, ?it/s]

### Fit online with custom environment

In [113]:
# setup algorithm
dqn = d3rlpy.algos.DQN()

# prepare experience replay buffer
buffer = d3rlpy.online.buffers.ReplayBuffer(maxlen=100000, env=env)

# prepare exploration strategy if necessary
explorer = d3rlpy.online.explorers.ConstantEpsilonGreedy(0.3)

# start data collection
dqn.fit_online(env, buffer, n_steps=100000)

2023-03-10 14:47:32 [info     ] Directory is created at d3rlpy_logs/DQN_online_20230310144732
2023-03-10 14:47:32 [debug    ] Building model...
2023-03-10 14:47:32 [debug    ] Model has been built.
2023-03-10 14:47:32 [info     ] Parameters are saved to d3rlpy_logs/DQN_online_20230310144732/params.json params={'action_scaler': None, 'batch_size': 32, 'encoder_factory': {'type': 'default', 'params': {'activation': 'relu', 'use_batch_norm': False, 'dropout_rate': None}}, 'gamma': 0.99, 'generated_maxlen': 100000, 'learning_rate': 6.25e-05, 'n_critics': 1, 'n_frames': 1, 'n_steps': 1, 'optim_factory': {'optim_cls': 'Adam', 'betas': (0.9, 0.999), 'eps': 1e-08, 'weight_decay': 0, 'amsgrad': False}, 'q_func_factory': {'type': 'mean', 'params': {'share_encoder': False}}, 'real_ratio': 1.0, 'reward_scaler': None, 'scaler': None, 'target_update_interval': 8000, 'use_gpu': None, 'algorithm': 'DQN', 'observation_shape': (1,), 'action_size': 5}


  0%|          | 0/100000 [00:00<?, ?it/s]

2023-03-10 14:48:12 [info     ] Model parameters are saved to d3rlpy_logs/DQN_online_20230310144732/model_10000.pt
2023-03-10 14:48:12 [info     ] DQN_online_20230310144732: epoch=1 step=10000 epoch=1 metrics={'time_inference': 0.0005066035032272339, 'time_environment_step': 1.2087106704711915e-05, 'time_step': 0.003947368121147155, 'time_sample_batch': 0.0001312981424975613, 'time_algorithm_update': 0.00323518305445813, 'loss': 1.49070639037667e-06} step=10000
2023-03-10 14:48:50 [info     ] Model parameters are saved to d3rlpy_logs/DQN_online_20230310144732/model_20000.pt
2023-03-10 14:48:50 [info     ] DQN_online_20230310144732: epoch=2 step=20000 epoch=2 metrics={'time_inference': 0.0004898247003555298, 'time_environment_step': 1.1702489852905273e-05, 'time_sample_batch': 0.00012943384647369385, 'time_algorithm_update': 0.003080199909210205, 'loss': 7.911302969334136e-07, 'time_step': 0.0037821149587631228} step=20000
2023-03-10 14:49:30 [info     ] Model parameters are saved to d3

In [146]:
for i in range(5):
    obs = np.array([i])
    action = dqn.predict([obs])[0]
    print(action)

### Fit on offline data generated from custom environment

In [147]:
#initialize the algorithm
dqn = d3rlpy.algos.DQN()

dataset2 = d3rlpy.online.buffers.ReplayBuffer(maxlen=100000, env=env)
dataset2 = buffer.to_mdp_dataset()
dataset2.load("random_policy_corridor_dataset.h5")

train_episodes, test_episodes = train_test_split(dataset2, test_size=0.2)

In [ ]:
# start training
dqn.fit(train_episodes,
        eval_episodes=test_episodes,
        n_epochs=5,
        scorers={
            'environment': evaluate_on_environment(env), # Cartpole environment
            'advantage': discounted_sum_of_advantage_scorer, # smaller is better
            'td_error': td_error_scorer, # smaller is better
            'value_scale': average_value_estimation_scorer # smaller is better
        })

In [148]:
dqn.fit(
    train_episodes,
    n_epochs=10,
    #scorers=metrics,
    eval_episodes=test_episodes,
)